# Generated by Django 4.2.5 on 2024-04-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gamestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestage',
            name='game_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
