# Generated by Django 4.2.5 on 2024-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_gamestage_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestage',
            name='game_name',
            field=models.CharField(max_length=10),
        ),
    ]
