# Generated by Django 4.2.5 on 2024-02-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
