# Generated by Django 4.2.5 on 2024-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestage',
            name='game_number',
        ),
        migrations.AddField(
            model_name='gamestage',
            name='sim_code',
            field=models.CharField(default='agenti_15', max_length=50),
        ),
    ]
